### ISSUE TITLE
IsInteresting 관련 처리

### ISSUE THREAD

**Issue by moconut** [warguss/ProjectRTS#115]
가까이 있는 유저들에게는 캐릭터의 상태정보(HP, 남은 무적시간과 같은 버프 등)를 UserSync패킷처럼 계속 주고받도록 처리하기. 멀리있으면 안 받고.
멀리있는 유저들에게는 기본적인 이벤트 정보만 받고 캐릭터를 화면에 그리지 않기.
이보다 더 벗어난 유저들은 아예 이벤트조차 받지않음.

**Comment by warguss** [comment]
처리완료, Intereteted에 대한 개념 통일 만 하면됨.
