### ISSUE TITLE
섹터 출입 유저와의 동기화

### ISSUE THREAD

**Issue by moconut** [warguss/ProjectRTS#56]
~플레이어가 한쪽으로 계속 움직여서 다른 섹터로 간다면?~
- ~한쪽으로 계속 움직이는 동안은 또다른 이벤트가 계속 발생하지 않기 때문에 고려 필요~
- sync패킷 전송으로 조치

다른 섹터에서 들어온 유저와 정보(남은 HP 표시 등) 동기화는 어떻게 하는가
- Hit 이벤트 및 Sync 이벤트에 남은 HP 프로퍼티 추가.

**Comment by moconut** [comment]
클라이언트가 서버측에게 특정 유저 정보(HP 등등)를 질의하는 패킷 타입 만들기.

**Comment by moconut** [comment]
서버에서 이벤트 패킷 전송 시 섹터 번호, 관심유저 여부도 함께 전송. 클라이언트에서는 이를 보고 관심유저, 비관심유저 분류. 비관심유저->관심유저가 될 경우 질의패킷 전송.

**Comment by moconut** [comment]
유저 정보 질의 계획 폐기. 이벤트 패킷에 남은 HP 프로퍼티를 추가함.

**Comment by warguss** [comment]
관심 유저, 비 관심 유저에 대한 로직 추가 필요함

**Comment by moconut** [comment]
무적상태 등의 동기화 필요함 spawn 시 3초 무적상태가 되는데, spawn이벤트를 받은 클라이언트에서만 무적인 걸로 보이고 다른 섹터에서 넘어온 플레이어에 대해선 무적상태로 안 보일 수 있음

**Comment by moconut** [comment]
새 이슈 생성
