### ISSUE TITLE
Server Refactoring 및 개발 사항

### ISSUE THREAD

**Issue by warguss** [warguss/ProjectRTS#62]
- ~~Lock Logic 개선, mutex, cond를 파라미터로 받고 락을 하는 형식으로 교체 필요함~~
= CThreadManager가 관리하는 형식이 아닌, 파라미터로 들고오는 Lock으로 변경

- ~~로그 생성 로직, Class 및 싱글톤으로 변경
(현재 #define으로 작업되어있음)
= 추가 이슈 (file에 쓸 때, Lock 및 해제 과정 이슈)~~
 #65 로깅 작업 완료

- Log 상세 필요
Event Receive , Event Send
Ex] 
성공 시, 
@SUCC  UID: (socketID) NName: (nickName) EType: (connect|noti|action) Sector: (int) DES: Recevie Succ
@FAIL UID: (socketID) NName: (nickName) EType: (connect|noti|action) Sector (int) DES: Recevie Error(connection Refuesed)
#68 로그 상세화 작업(완료는 아니지만 일부분 구현완료) 

- daemon 구조 생성
= ~~daemon 구조 필요 (완료)~~

- 로그레벨 분리
= 현재 다 쓴다. (이부분은 추후 분리)

- 섹터를 현재보다 작은 크기로 구성. 관심 범위는 플레이어 주변의 다수의 섹터를 포함하도록 구성.
  - 섹터 크기 및 관심 범위를 변경하기 쉽게 코딩하면 좋을 듯
#60 섹터관련 작업

**Comment by moconut** [comment]
- 이벤트 전송 대상 : 현재 섹터를 중심으로 5*5범위 섹터.
- 관심유저 구분 대상 : 현재 섹터를 중심으로 3*3범위 섹터.
- 범위는 변할 수 있음.

**Comment by moconut** [comment]
서버에서 유저에게 이벤트를 송신할 때, 이 이벤트를 일으킨 유저는 이벤트 정보를 수신받을 유저에게 관심유저인지 아닌지 정보를 담아서 전송. 이벤트 패킷에 isInterested프로퍼티 추가.

-> Client쪽에서 isInterested를 받아 처리하기보다 Server측에서 관심영역 구분후 주는 형식으로 변경됨,
완료
#69

**Comment by warguss** [comment]
- ~~관심 유저 작업 필요~~
= ~~영역 범위에 대한 관심 유저 설정 필요(패킷에 담아 보내야함)~~
(Server 측 작업으로 변경, 완료)

- ~~비관심 유저에 대한 패킷 전달은 완료~~

- 노티의 경우 Death -> Server Push 방식으로 진행
= ~~기본 Action Death에 대해서는, 구역 전송, Noti(누가 누굴죽였는지)에 대한 정보는 All Send 완료~~
- ~~Death는 Part Event로 진행한다~~
#71 위 두이슈 에대한 PR
