### ISSUE TITLE
무기선택개념

### ISSUE THREAD

**Issue by moconut** [warguss/ProjectRTS#70]
캐릭터가 현재 들고있는 무기, 무기에 따른 공격의 변화 구현 필요.
무기별로 DamageInfo를 다르게, 매 프레임 탄환의 위치를 계산하는 메소드를 다르게 구현하면 되지 않을까.
Bullet 클래스를 상속받아 여러 탄환 클래스 작성.

**Comment by warguss** [comment]
- Proto 정의 필요
- 무기를 들고 있는거에 대한 Proto 정의가 필요함

**Comment by moconut** [comment]
현재는 러프하게 구현, 추후 '무기'클래스를 만들어 내부에 남은 탄환 수, shoot메소드를 구현하는 식으로 구체화 해야함. 
shoot메소드 내부에서 발사딜레이 체크하여 발사가능여부 체크

**Comment by moconut** [comment]
캐릭터 내에 현재 보유중인 무기를 리스트로 저장하게 하기

**Comment by moconut** [comment]
무기 획득 구현 필요

**Comment by moconut** [comment]
PlayerWeapon클래스 작성. 발사 가능상태를 체크하여 bullet 생성함. 
현재 탄속, 탄환 범위는 무기 종류에 따라 항상 일정하게 되어있어 네트워크에 반영이 안됨. 이를 반영하려면 DamageInfo클래스를 수정해야함.

**Comment by moconut** [comment]
탄환 범위, 탄속 동기화시킴.
HitType을 넣어 데미지 입을 시 이에따라 분기시켜 맞았을 때의 행동 정의 가능.

**Comment by moconut** [comment]
한 캐릭터가 몇개의 무기까지 가질 수 있게 해야하는가. 
무기 습득 시 최대 가질 수 있는 무기의 갯수를 넘어서면 획득 불가. 무기 버리기 기능 제공. 이미 가지고 있는 무기의 경우 탄환 추가하도록 구현 예정.
