### ISSUE TITLE
필드 내 아이템 생성, 습득 구현

### ISSUE THREAD

**Issue by moconut** [warguss/ProjectRTS#93]
아이템 생성 로직 및 타 플레이어들과 동기화 방법?
아이템 습득 관련 패킷 정의 - 아이템 1갠데 둘이서 동시에 습득하는 일 방지해야 함

**Comment by warguss** [comment]
+ 유저의 비율을 고려한 아이템 생성

**Comment by moconut** [comment]
로직에서 아이템 생성 및 습득에 대한 코드는 작성됨.

**Comment by warguss** [comment]
겹친 이슈존재로 close
